baseURL = "https://yatingliu2019.github.io/"
title = "Liuyating's Blog"
author = "Steve Francia"
copyright = "© 2025, lyt.so"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
[pagination]
  pagerSize = 3

# ------------------------------
# theme = "hugo-paper"
publishDir = "docs"
buildDrafts = true
buildFuture = false
buildExpired = false

[params]
  color = 'linen'
  github = 'yatingliu2019'
  mastodon = 'https://blog.csdn.net/qq_51870267?spm=1011.2415.3001.5111'

avatar = 'https://yatingliu2019.github.io/images/p1.jpg'
  name = 'Liuyating'
  bio = '理解万岁'
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "教育及科研经历"
    url = "/about/"
    weight = 8
  [[menu.main]]
    identifier = "contact"
    name = "联系方式"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.x]
    disableInlineCSS = true

[module]
  [[module.imports]]
    path = "hugo-paper"
